development:
  secret_key_base: 9dxx7e
  db_user: <%= ENV["root"] %>
  db_pass: <%= ENV["1234"] %>

test:
  secret_key_base: 3cxxx45
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>
